version: '3'
name: 'jti-test'
services: 
  db:
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abcd1234
      MYSQL_DATABASE: default_schema
      MYSQL_USER: jtitest
      MYSQL_PASSWORD: abcd1234
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
  jti:
    image: jtitest:latest
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - db
volumes:
  mysql:
