version: '3'
name: 'jti-test'
services: 
  db:
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abcd1234
      MYSQL_DATABASE: default_schema
      MYSQL_USER: jtitest
      MYSQL_PASSWORD: abcd1234
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
  jti:
    image: jtitest:latest
    restart: always
    ports:
      - 8082:8082
    environment:
      - JWT_SECRET=abc5dasar
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=abcd1234
      - DB_NAME=jti_test
      - GOOGLE_CLIENT_ID=client_id
      - GOOGLE_CLIENT_SECRET=client_secret
      - GOOGLE_REDIRECT_URL=http://localhost:8082/api/auth/login/google/callback
    depends_on:
      - db
volumes:
  mysql:
